#include <stdio.h>
#include "test_random.h"
#include <time.h>
#include "myrand.h"

void test_random(int seed, int n, long int* random){
	int i, r;
	int mycount[] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
	int count[] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
	
	for(i=0; i<n; ++i){
		r = 1 + rand() % 15;
//		/* to check numbers*/
//		printf("%d - my rand: %d\t\t rand: %d\n", i+1, random[i], r); 
		
		/* count numbers 1-15 which are generated by myrand() and rand() */
		switch (random[i]){
			case 1:
				mycount[0] +=1;
				break;
			case 2:
				mycount[1] +=1;
				break;
			case 3:
				mycount[2] +=1;
				break;
			case 4:
				mycount[3] +=1;
				break;
			case 5:
				mycount[4] +=1;
				break;
			case 6:
				mycount[5] +=1;
				break;
			case 7:
				mycount[6] +=1;
				break;
			case 8:
				mycount[7] +=1;
				break;
			case 9:
				mycount[8] +=1;
				break;
			case 10:
				mycount[9] +=1;
				break;
			case 11:
				mycount[10] +=1;
				break;
			case 12:
				mycount[11] +=1;
				break;
			case 13:
				mycount[12] +=1;
				break;
			case 14:
				mycount[13] +=1;
				break;
			case 15:
				mycount[14] +=1;
				break;		
		}

		switch (r){
			case 1:
				count[0] +=1;
				break;
			case 2:
				count[1] +=1;
				break;
			case 3:
				count[2] +=1;
				break;
			case 4:
				count[3] +=1;
				break;
			case 5:
				count[4] +=1;
				break;
			case 6:
				count[5] +=1;
				break;
			case 7:
				count[6] +=1;
				break;
			case 8:
				count[7] +=1;
				break;
			case 9:
				count[8] +=1;
				break;
			case 10:
				count[9] +=1;
				break;
			case 11:
				count[10] +=1;
				break;
			case 12:
				count[11] +=1;
				break;
			case 13:
				count[12] +=1;
				break;
			case 14:
				count[13] +=1;
				break;
			case 15:
				count[14] +=1;
				break;
		} //count ends
		
		if(i == (n-1))
			printf("\n");
		
	} //for ends
	
	float mynorm, norm, myperc, perc;
	
	/* calculate normalized results of the generated numbers */
	printf("*results from myrand()*\t\t*results from rand()*\n");
	for(i=0; i<15; ++i){
		
		myperc = mycount[i] * 100;
		myperc /= n;
		perc = count[i] * 100;
		perc /= n;
		mynorm = myperc / 100;
		norm = perc / 100;
		
		printf("%d = %f (%%%.3f)\t\t%d = %f (%%%.3f)\n", i+1, mynorm, myperc, i+1, norm, perc);
	}
	
}
